aruco_detector:
  ros__parameters:
    marker_size: 0.5

    # 0 = Exploration, 1 = Precision Landing
    active_mission_state: 1
    detect_only_active_state: true

    # -1이면 가장 크게 보이는 marker 사용
    target_marker_id: -1

    dictionary: "DICT_4X4_50"

    # echo 로그에서 frame이 x500_gimbal_0/camera_link/camera로 나왔으므로 기본값을 맞춤
    default_camera_frame_id: "x500_gimbal_0/camera_link"

    # map 좌표 변환 목표 frame
    target_frame: "map"
    publish_map_pose: true

    write_csv: true
    csv_file_path: ""

    # 기존 파일 방식과 유사한 좌표 변환 사용
    # ROS x = -OpenCV z, ROS y = OpenCV x, ROS z = -OpenCV y
    convert_opencv_to_ros: true
