asp_final_uav_mission_node:
  ros__parameters:
    waypoint_path: mission2_uav_waypoints.csv
    map_frame: map
    base_frame: x500_gimbal_0/base_link
    ugv_base_frame: X1_asp/base_link
    ugv_landing_frame: X1_asp/aruco_marker_10_link
    control_period_s: 0.2
    takeoff_altitude_m: 10.0
    waypoint_tolerance_m: 1.2
    waypoint_timeout_s: 14.0
    marker_action_timeout_s: 4.0
    hold_after_takeoff_s: 0.0
    takeoff_complete_timeout_s: 3.0
    default_yaw_rad: 0.0
    enable_mission2_transition_corridor: true
    transition_corridor_max_step_m: 10.0
    transition_corridor_min_cruise_altitude: 24.0
    transition_corridor_max_cruise_altitude: 34.0
    transition_corridor_hold_sec: 1.0
    transition_corridor_gimbal_pitch_deg: -60.0
    transition_corridor_tag_prefix: "mission2_transition"
    waypoint_arrival_mode: "xy_z_separate"
    waypoint_xy_tolerance_m: 2.5
    waypoint_z_tolerance_m: 3.0
    ignore_yaw_for_waypoint_reached: true
    yaw_tolerance_deg: 45.0
    waypoint_stuck_timeout_sec: 12.0
    max_same_waypoint_sec: 15.0
    force_advance_on_stuck: true
    force_advance_when_xy_close: true
    xy_close_timeout_sec: 5.0
    continue_on_marker_timeout: true
    marker_wait_timeout_sec: 3.0
    do_not_block_waypoint_progress_on_marker: true
    landing_hover_altitude_m: 4.0
    landing_descent_step_m: 1.0
    landing_complete_altitude_m: 3.0
    landing_timeout_s: 30.0
    landing_detection_timeout_s: 2.0
    landing_approach_altitude_m: 8.0
    landing_xy_tolerance_m: 1.0
    landing_marker_id: 10
    landing_marker_max_ugv_distance_m: 2.0
