asp_final_uav_mission_node:
  ros__parameters:
    waypoint_path: mission2_uav_waypoints.csv
    map_frame: map
    base_frame: x500_gimbal_0/base_link
    ugv_base_frame: X1_asp/base_link
    ugv_landing_frame: X1_asp/base_link
    control_period_s: 0.2
    takeoff_altitude_m: 10.0
    waypoint_tolerance_m: 1.2
    waypoint_timeout_s: 20.0
    marker_action_timeout_s: 4.0
    hold_after_takeoff_s: 0.0
    takeoff_complete_timeout_s: 3.0
    enable_mission1_preoffboard_preroll: false
    default_yaw_rad: 0.0
    enable_mission2_transition_corridor: true
    transition_corridor_max_step_m: 10.0
    transition_corridor_min_cruise_altitude: 10.0
    transition_corridor_max_cruise_altitude: 34.0
    transition_corridor_hold_sec: 1.0
    transition_corridor_gimbal_pitch_deg: -60.0
    transition_corridor_tag_prefix: "mission2_transition"
    waypoint_arrival_mode: "xy_z_separate"
    waypoint_xy_tolerance_m: 1.8
    waypoint_z_tolerance_m: 1.0
    ignore_yaw_for_waypoint_reached: true
    yaw_tolerance_deg: 45.0
    waypoint_stuck_timeout_sec: 18.0
    max_same_waypoint_sec: 20.0
    force_advance_on_stuck: true
    force_advance_when_xy_close: false
    xy_close_timeout_sec: 5.0
    continue_on_marker_timeout: false
    marker_wait_timeout_sec: 8.0
    do_not_block_waypoint_progress_on_marker: true
    mission2_complete_preposition_enabled: true
    prelanding_altitude_m: 8.0
    prelanding_gimbal_pitch_deg: -90.0
    prelanding_target_lock_xy_tolerance_m: 2.0
    landing_prealign_xy_tolerance_m: 2.5
    landing_hover_altitude_m: 4.0
    landing_descent_step_m: 0.6
    landing_complete_altitude_m: 0.02
    landing_timeout_s: 30.0
    landing_detection_timeout_s: 2.0
    landing_approach_altitude_m: 1.5
    landing_touchdown_setpoint_m: 0.10
    landing_touchdown_offset_m: 0.25
    landing_target_lock_altitude_m: 0.8
    landing_land_command_height_tolerance_m: 0.10
    landing_touchdown_disarm_height_tolerance_m: 0.15
    landing_xy_tolerance_m: 1.0
    landing_final_descent_xy_tolerance_m: 0.70
    landing_land_command_xy_tolerance_m: 0.70
    landing_touchdown_disarm_xy_tolerance_m: 0.35
    landing_land_command_stable_sec: 0.5
    landing_marker_loss_descent_xy_tolerance_m: 0.8
    landing_marker_id: 10
    landing_marker_max_ugv_distance_m: 2.0
    landing_final_descent_requires_marker: true
    landing_use_detection_pose_as_target: true
    landing_detection_update_min_altitude_m: 2.0
    landing_detection_update_max_step_m: 0.7
    landing_send_px4_land_command: true
    landing_target_offset_body_x_m: 0.0
    landing_target_offset_body_y_m: 0.60
